### PR TITLE
Create House_Python

### PR DESCRIPTION
**Pull request by esk22**
Uploaded the python code for our house app. Still working with decision making to decide if using this will be necessary.

### CODE REVIEW

**Comment by jasedit** [comment]
I don't think we need a port of the house app to python. They should be speaking to the house through the Device API, and the house app is something they are unaware of directly.

**Comment by esk22** [comment]
Sounds good, I had it done so I uploaded it. I email the decision making
guys and trying to work out what they need from us.

**Comment by jasedit** [comment]
I'm going to close this, as we don't need a version of the House in Python.

**Comment by esk22** [comment]
Sounds good

**Pull request closed without merging**
