### PR TITLE
Fix house output

### PR DESCRIPTION
**Pull request by jasedit**
This matches the House Output as expected by the House app, and integrated with what we expect from server inputs.

### CODE REVIEW

**Comment by jasedit** [comment]
@bkicia If you get a chance, could you check this out and see if it works for you?

**Comment by bwegryn** [comment]
@jasedit the code compiles, but the unit test below fails:

Assert.IsTrue(testHO.write(new AlarmSystem(null, null, null)));

**Comment by jasedit** [comment]
Good spot - the tests for HouseOutput has been moved over to the HouseTest unit testing, for which execution instructions for Mac [here](https://scholar.vt.edu/portal/site/aa63a240-bbcf-4342-b3de-ed2515c28e16/page/f6ab320f-c070-49be-8bf3-85ee9d542302)

**Comment by jasedit** [comment]
@suwarna07 Just verified that this branch correctly communicates with the ServerAPI.

**Pull request merged**
