### PR TITLE
Added IODevices to setters/getters and update

### PR DESCRIPTION
**Pull request by willrd9**

### CODE REVIEW

**Comment by jasedit** [comment]
What happens if the Input/Output objects are null?

**Comment by jasedit** [comment]
Also, the formatting got completely hammered into an invalid state here. I can fix this with a force push.

**Comment by willrd9** [comment]
That's a good question. If I return the error then it would go to the same place as the null and result in a error later down the line anyway right? Also what does it mean for an invalid state?

**Comment by jasedit** [comment]
We could either return the last valid value, and ask the client to check the LastUpdated value, or we could add an additional property which is read-only and indicates if the last communication succeeded.

**Comment by willrd9** [comment]
Can I require all of the function arguments to include a bool pointer and set that within the function?

**Comment by jasedit** [comment]
Not with properties - C# makes them look/act like public member variables, but not actually operating in that fashion.

**Comment by willrd9** [comment]
Oh okay I was unsure. I think it would be better to add another property indicative of successful communication. I can implement probably before this evening.

**Comment by jasedit** [comment]
Just a heads up - I fixed the formatting that had been thrown out of spec with a force push. If you grab it, it keeps the line endings correct, and eliminates a lot of other minor issues (although not all - according to coding standard, if/else statements should have brackets) to clean things up. It makes the branch act a bit funny (you need to delete your local branch, then fetch, and check out the branch again.) but it cleans up considerably.

**Comment by jasedit** [comment]
Specific device classes need to interact with the deviceinput/deviceoutput still, but this is good enough for the base class. Unit tests now pass, merging!

**Pull request merged**
