### PR TITLE
Changes: TimeFrame, server address, asyn read.

### PR DESCRIPTION
**Pull request by arunkt1**

### CODE REVIEW

**Comment by arunkt1** [comment]
In case a merge is not possible, I can create changes to a new branch from master.

**Comment by jasedit** [comment]
@arunkt1 Please verify that the ServerInput works as you intend - it seems to be acting strangely for me. However, the code has been rebased onto master, and is now ready to merge once the ServerInput is fixed and you verify the rebase.

**Comment by arunkt1** [comment]
The commits seems to be acting funny. I will make the necessary changes.

**Comment by jasedit** [comment]
Yes - it's the result of the rebase operation. Switch to some other branch, delete your local copy of the branch, and check it back out. Or, as a copy-paste job:

```
git checkout origin/master; git branch -D enum_dev_io-2; git checkout enum_dev_io-2
```

**Comment by arunkt1** [comment]
I have done that. Thanks Jason.

**Comment by arunkt1** [comment]
Is response.StatusCode == HttpStatusCode.OK not giving back a true for you?

**Comment by jasedit** [comment]
There are other StatusCodes which are considered success, but aren’t OK (e.g. NoContent)

**Comment by arunkt1** [comment]
Oh ok. I shall check both these conditions then.

**Comment by jasedit** [comment]
The IsSuccessStatusCode automatically checks for all the successful status codes, and is sufficient for verifying you have a valid result.

**Comment by arunkt1** [comment]
The tests for ServerInputs are not showing during test run. I am looking into that now.

**Comment by arunkt1** [comment]
Seems to be the problem of the server API. I think the code is right as enumerate devices () is passing the test.

**Comment by jasedit** [comment]
If you have confirmation from them that the result you are receiving is expected, let me know and we can merge.

**Comment by arunkt1** [comment]
the url seems to be working in postman. Not really sure what is happening as the exact same Http call is working for enumerate devices ().

**Comment by jasedit** [comment]
What are you getting from using Postman? Looking at the URL, you may be getting responses from the persistent storage system, which wouldn't contain data to update a device with.

**Comment by arunkt1** [comment]
I am getting a 200 ok. But there is no content which is getting returned.

**Comment by arunkt1** [comment]
It seems a bit strange as I remember server Input test passing before.

**Comment by jasedit** [comment]
If you are calling a get for a device, and not getting any data, it isn't actually returning valid data. Is this expected?

**Comment by arunkt1** [comment]
we are passing 0/0/0 as the three IDs. The same stuff does not return anything in Postman. Therefore I think it is expected.

**Comment by jasedit** [comment]
Hmm - for me, the ServerInput test is hanging without completion. Is there some trick to getting data from the server?

**Comment by arunkt1** [comment]
Since they are not passing anything I am not able to come up with anything. I am not able to find anything wrong with the code either.

**Pull request merged**
